# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prima.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_prima(object):
    def setupUi(self, prima):
        prima.setObjectName("prima")
        prima.resize(400, 300)
        self.gotosecBtn = QtWidgets.QPushButton(prima)
        self.gotosecBtn.setGeometry(QtCore.QRect(150, 130, 93, 28))
        self.gotosecBtn.setObjectName("gotosecBtn")
        self.exitbtn = QtWidgets.QPushButton(prima)
        self.exitbtn.setGeometry(QtCore.QRect(150, 170, 93, 28))
        self.exitbtn.setObjectName("exitbtn")
        self.label = QtWidgets.QLabel(prima)
        self.label.setGeometry(QtCore.QRect(150, 90, 55, 16))
        self.label.setObjectName("label")

        self.retranslateUi(prima)
        QtCore.QMetaObject.connectSlotsByName(prima)

    def retranslateUi(self, prima):
        _translate = QtCore.QCoreApplication.translate
        prima.setWindowTitle(_translate("prima", "Form"))
        self.gotosecBtn.setText(_translate("prima", "seconda"))
        self.exitbtn.setText(_translate("prima", "esci"))
        self.label.setText(_translate("prima", "prima"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    prima = QtWidgets.QWidget()
    ui = Ui_prima()
    ui.setupUi(prima)
    prima.show()
    sys.exit(app.exec_())
